### ISSUE TITLE
Add PrefixSet.PrefixSeq and PrefixSet.PrefixCompactSeq for Go 1.23+

### ISSUE THREAD

**Issue by database64128** [aromatt/netipds#12]
Serializing large prefix sets will become much more efficient, if we can avoid allocating the intermediate slice by allowing iterator access over the prefixes. I propose we add:

```go
func (s *PrefixSet) PrefixSeq() iter.Seq[netip.Prefix]
func (s *PrefixSet) PrefixCompactSeq() iter.Seq[netip.Prefix]
```

Alternatively, give the existing `Prefixes` and `PrefixesCompact` names to the new iterator methods, to align with the [naming conventions](https://pkg.go.dev/iter#hdr-Naming_Conventions).

I'd be happy to work on this and open a PR.

Related proposal at netipx: go4org/netipx#21

**Comment by aromatt** [comment]
Hi @database64128, thanks for filing this issue. Iterators are definitely on my roadmap for this library. A PR would be much appreciated, if you're up for it.

I'll get back to you about naming (and I'm open to further discussion about it). Relevant context: I have made an effort to mirror the naming patterns of netipx wherever it makes sense. While not perfect, this is part of an explicit goal of netipds to fit in with netip/netipx.

**Comment by database64128** [comment]
Thanks. I went with `PrefixSeq`, `PrefixCompactSeq` and opened #13.
